---
# NOTE: Usually you'd install a Consul client on the Vault nodes and use it to
# register the service in Consul. But in this setup, it would create a
# bidirectional dependency between Vault and Consul.
#
# Instead we are using Consul's HTTP API to keep the dependency chain simple:
#
#     Vault <-(depends on)- Consul <-(depends on)- Nomad
#
- name: Register Vault as Consul service
  run_once: true
  ansible.builtin.uri:
    url: http://127.0.0.1:8500/v1/catalog/register
    method: PUT
    body_format: json
    body:
      Node: "{{ item }}"
      Address: "{{ hostvars[item]['ansible_' + network_interface]['ipv4']['address'] }}"
      NodeMeta:
        external-node: "true"
        external-probe: "true"
      Service:
        Service: vault
        Tags: []
        Port: 8200
      Check:
        Name: "Vault health check"
        ServiceID: vault
        Definition:
          HTTP: "http://{{ hostvars[item]['ansible_' + network_interface]['ipv4']['address'] }}:8200/v1/sys/health"
          TLSSkipVerify: false
          Interval: "10s"
          Timeout: "2s"
  with_items: "{{ groups['vault'] }}"
