---
version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "docker"
    directory: "/.github/actions/lint"
    schedule:
      interval: "monthly"

  - package-ecosystem: "docker"
    directory: "/nomad_jobs/hello-world-vault"
    schedule:
      interval: "monthly"
