---
- name: Create data directory
  ansible.builtin.file:
    path: "{{ vault_data_dir }}"
    state: directory
    owner: vault
    group: vault
    mode: 0755
  when: vault_mode == 'server'

- name: Copy config
  ansible.builtin.template:
    src: "vault-server.hcl.j2"
    dest: "/etc/vault.d/vault.hcl"
    mode: 0644
