---
- hosts: vault
  become: yes
  roles:
    # Create self-signed root CA for entire project
    - name: base/create-root-ca

    # Vault specific setup
    - name: base/apt
    - name: base/copy-root-ca
    - name: syslog-ng
    - name: vault/installation
    - name: vault/intermediate-ca
    - name: vault/nomad-token
    - name: vault/prometheus-metric-access
    - name: vault/secret-alertmanager
    - name: vault/secret-grafana
    - name: vault/secret-hello-world
