---
- hosts: worker
  become: yes
  roles:
    - name: base/apt
    - name: base/copy-root-ca
    - name: consul/installation
      vars:
        consul_mode: client
    - name: nomad/driver-jre
    - name: nomad/driver-docker
    # - name: vault  # client only
    - name: nomad/installation
      vars:
        nomad_mode: client

  post_tasks:
    - name: Disable systemd-resolved service
      systemd:
        name: systemd-resolved
        state: stopped
        enabled: no
      tags: ['always']

    - name: Set nameserver to localhost
      copy:
        content: "nameserver {{ loadbalancer_ip }}"
        dest: /etc/resolv.conf
        mode: 0644
      tags: ['always']

    - name: Restart Docker to pick up DNS change
      systemd:
        name: docker
        state: restarted
      tags: ['docker']
