---
- hosts: localhost
  become: no
  roles:
    # Create self-signed root CA for entire project
    - name: base/create-root-ca

- hosts: all, !localhost
  become: yes
  roles:
    - name: base/prerequisites
    - name: base/ufw
    - name: base/copy-root-ca
    - name: node_exporter

- hosts: tools
  become: yes
  roles:
    - name: coredns
    - name: syslog-ng
    - name: consul/maintenance-snapshot
    - name: nomad/maintenance-snapshot

- hosts: vault
  become: yes
  roles:
    - name: base/set-nameserver
    - name: syslog-ng
    - name: vault/installation
    - name: vault/intermediate-ca
    - name: vault/nomad-token
    - name: vault/prometheus-metric-access
    - name: vault/secret-alertmanager
    - name: vault/secret-grafana
    - name: vault/secret-hello-world

- hosts: controlplane
  become: yes
  roles:
    - name: base/set-nameserver
    - name: vault/installation
      vars: [ vault_mode: client ]
      when: vault_enable_tls | bool
    - name: consul/installation
    # - name: consul/register-vault-service
    - name: nomad/installation

- hosts: worker
  become: yes
  roles:
    - name: base/set-nameserver
    - name: vault/installation
      vars: [ vault_mode: client ]
      when: vault_enable_tls | bool
    - name: consul/installation
      vars: [ consul_mode: client ]
    - name: nomad/driver-jre
    - name: nomad/driver-docker
    - name: nomad/installation
      vars: [ nomad_mode: client ]

- hosts: loadbalancer
  become: yes
  roles:
    - name: base/set-nameserver
    - name: vault/installation
      vars: [ vault_mode: client ]
      when: vault_enable_tls | bool
    - name: traefik
