---
- hosts: vault
  become: yes
  tasks:
    - name: Get Vault status # noqa no-changed-when
      ansible.builtin.command: vault status -format json
      environment:
        VAULT_ADDR: "{{ vault_addr }}"
      register: _vault_status_results
      failed_when: _vault_status_results.rc == 1

    - name: Parse output of 'vault status'
      ansible.builtin.set_fact: _vault_status_parsed="{{ _vault_status_results.stdout | from_json }}"

    - name: Unseal Vault
      ansible.builtin.include_tasks: roles/vault/installation/tasks/unseal.yml
      when: _vault_status_parsed.sealed
