---
- name: Enable key-value secret engine # noqa no-changed-when
  no_log: yes
  ansible.builtin.command: vault secrets enable -version=1 kv
  register: _vault_kv_enable_result
  failed_when:
    - _vault_kv_enable_result.rc > 0
    - '"path is already in use" not in _vault_kv_enable_result.stderr'
  environment:
    VAULT_ADDR: "{{ vault_addr }}"
    VAULT_TOKEN: "{{ vault_root_token }}"

- name: Store admin credentials for 'grafana' # noqa no-changed-when
  no_log: yes
  ansible.builtin.command: |
    vault kv put kv/monitoring/grafana
      username='admin'
      password='{{ lookup('password', playbook_dir + '/credentials/grafana_admin.creds length=8 chars=ascii_letters,digits') }}'
  environment:
    VAULT_ADDR: "{{ vault_addr }}"
    VAULT_TOKEN: "{{ vault_root_token }}"

- name: Copy 'monitoring-grafana' policy
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/nomad_jobs/monitoring-grafana-policy.vault"
    dest: "/home/{{ ansible_ssh_user }}/monitoring-grafana-policy.vault"
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
    mode: 0644

- name: Write 'monitoring-grafana' policy to Vault # noqa no-changed-when
  no_log: yes
  ansible.builtin.command: "vault policy write monitoring-grafana /home/{{ ansible_ssh_user }}/monitoring-grafana-policy.vault"
  environment:
    VAULT_ADDR: "{{ vault_addr }}"
    VAULT_TOKEN: "{{ vault_root_token }}"
