---
- name: Enable key-value secret engine # noqa no-changed-when
  no_log: yes
  shell: vault secrets enable -version=1 kv || true
  environment:
    VAULT_ADDR: "{{ vault_addr }}"
    VAULT_TOKEN: "{{ vault_root_token }}"

# EXAMPLES:
# - name: Store SMTP credentials for 'alertmanager' # noqa no-changed-when
#   no_log: yes
#   command: |
#     vault kv put kv/monitoring/alertmanager/smtp
#       smarthost='mail.example.com:25'
#       username='admin'
#       password='pa$$w0rd'
#   environment:
#     VAULT_ADDR: "{{ vault_addr }}"
#     VAULT_TOKEN: "{{ vault_root_token }}"

# - name: Store PagerDuty credentials for 'alertmanager' # noqa no-changed-when
#   no_log: yes
#   command: |
#     vault kv put kv/monitoring/alertmanager/pagerduty
#       service_key='ABC1234567890'
#   environment:
#     VAULT_ADDR: "{{ vault_addr }}"
#     VAULT_TOKEN: "{{ vault_root_token }}"

- name: Copy 'monitoring-alertmanager' policy
  copy:
    src: "{{ playbook_dir }}/nomad_jobs/monitoring-alertmanager-policy.vault"
    dest: "/home/{{ ansible_ssh_user }}/monitoring-alertmanager-policy.vault"
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
    mode: 0644

- name: Write 'monitoring-alertmanager' policy to Vault # noqa no-changed-when
  no_log: yes
  command: "vault policy write monitoring-alertmanager /home/{{ ansible_ssh_user }}/monitoring-alertmanager-policy.vault"
  environment:
    VAULT_ADDR: "{{ vault_addr }}"
    VAULT_TOKEN: "{{ vault_root_token }}"
