---
- name: Add OpenJDK PPA
  ansible.builtin.apt_repository:
    repo: "ppa:openjdk-r/ppa"
    state: present

- name: Install OpenJDK Java Runtime Environment (Headless)
  ansible.builtin.package:
    name: "openjdk-{{ openjdk_version }}-jre-headless"
    state: present
