---
- name: Include default settings
  ansible.builtin.include_vars: file=defaults/main.yml name=defaults

- name: Install ufw
  ansible.builtin.package: name=ufw state=present

- name: Set default rule - Deny all incoming traffic
  ansible.builtin.ufw: policy=deny direction=incoming

- name: Check SSH access firewall rule
  ansible.builtin.fail: msg="SECURITY CHECK - Don't allow SSH access from {{ defaults.ufw_allow_ssh_from }} outside the Vagrant demo environment! Aborting."
  when:
    - vagrant is not defined
    - ufw_allow_ssh_from == defaults.ufw_allow_ssh_from

- name: Allow SSH access
  ansible.builtin.ufw: rule=allow src="{{ ufw_allow_ssh_from }}" port=22

- name: Allow all access from internal network and load balancer
  ansible.builtin.ufw: rule=allow src="{{ item }}"
  loop:
    - "{{ vagrant_internal_network_range }}"
    - "{{ vagrant_loadbalancer_ip }}"
  when: "'loadbalancer' not in inventory_hostname"

- name: Allow DNS access to load balancer
  ansible.builtin.ufw:
    rule=allow port=53 proto="{{ item }}"
  loop:
    - tcp
    - udp
  when: "'loadbalancer' in inventory_hostname"

- name: Allow access to load balancer
  ansible.builtin.ufw: rule=allow port="{{ item }}"
  loop:
    - 80
    - 443
    - 8200
  when: "'loadbalancer' in inventory_hostname"

- name: Enable firewall
  ansible.builtin.ufw: state=enabled
