---
- name: Copy 'prometheus-policy'
  copy:
    src: "{{ playbook_dir }}/nomad_jobs/monitoring-prometheus-policy.vault"
    dest: "/home/{{ ansible_ssh_user }}/monitoring-prometheus-policy.vault"
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
    mode: 0644

- name: Write 'prometheus-policy' to Vault # noqa no-changed-when
  no_log: yes
  command: "vault policy write monitoring-prometheus /home/{{ ansible_ssh_user }}/monitoring-prometheus-policy.vault"
  environment:
    VAULT_ADDR: "{{ vault_addr }}"
    VAULT_TOKEN: "{{ vault_root_token }}"
