---
- name: Download GPG key
  ansible.builtin.get_url:
    url: https://ose-repo.syslog-ng.com/apt/syslog-ng-ose-pub.asc
    dest: /usr/share/keyrings/syslog-ng-ose-archive-keyring.asc
    mode: 0644

- name: De-armor GPG key # noqa no-changed-when
  ansible.builtin.command: |
    gpg --dearmor
    --output /usr/share/keyrings/syslog-ng-ose-archive-keyring.gpg
    /usr/share/keyrings/syslog-ng-ose-archive-keyring.asc

- name: Remove ASCII version of GPG key
  ansible.builtin.file:
    path: /usr/share/keyrings/syslog-ng-ose-archive-keyring.asc
    state: absent

- name: Add apt repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/syslog-ng-ose-archive-keyring.gpg] https://ose-repo.syslog-ng.com/apt/ stable ubuntu-{{ ansible_distribution_release }}"
    filename: syslog-ng
    state: present

- name: Install syslog-ng-core
  ansible.builtin.package: name=syslog-ng-core state=present

- name: Extract major and minor version (reqired for config file) # noqa no-changed-when
  ansible.builtin.shell: |
    set -o pipefail
    syslog-ng --version | grep -Po 'Config version: \K\d+\.\d+'
  args:
    executable: /bin/bash
  register: _syslog_ng_version_parsed

- name: Parse output of 'syslog-ng --version'
  ansible.builtin.set_fact: syslog_ng_version={{ _syslog_ng_version_parsed.stdout }}

- name: Deploy syslog-ng client config on Vault nodes
  ansible.builtin.include_tasks: client.yml
  when: "'vault' in group_names"

- name: Deploy syslog-ng upstream config on non-Vault node
  ansible.builtin.include_tasks: upstream.yml
  when: "'vault' not in group_names"

- name: Copy systemd service
  ansible.builtin.copy:
    src: "syslog-ng.service"
    dest: "/etc/systemd/system/syslog-ng.service"
    mode: 0644

- name: Start syslog-ng service
  ansible.builtin.systemd:
    name: syslog-ng
    state: restarted
    daemon_reload: yes
    enabled: yes
