---
- name: Add apt key
  apt_key:
    url: "https://ose-repo.syslog-ng.com/apt/syslog-ng-ose-pub.asc"
    state: present

- name: Add apt repository
  apt_repository:
    repo: "deb https://ose-repo.syslog-ng.com/apt/ stable ubuntu-{{ ansible_distribution_release }}"
    filename: syslog-ng
    state: present

- name: Install syslog-ng-core
  package: name=syslog-ng-core state=present

- name: Extract major and minor version (reqired for config file) # noqa no-changed-when
  shell: |
    set -o pipefail
    syslog-ng --version | grep -Po 'Config version: \K\d+\.\d+'
  args:
    executable: /bin/bash
  register: _syslog_ng_version_parsed

- name: Parse output of 'syslog-ng --version'
  set_fact: syslog_ng_version={{ _syslog_ng_version_parsed.stdout }}

- name: Deploy syslog-ng client config on Vault nodes
  include_tasks: client.yml
  when: "'vault' in group_names"

- name: Deploy syslog-ng upstream config on non-Vault node
  include_tasks: upstream.yml
  when: "'vault' not in group_names"

- name: Copy systemd service
  copy:
    src: "syslog-ng.service"
    dest: "/etc/systemd/system/syslog-ng.service"
    mode: 0644

- name: Start syslog-ng service
  systemd:
    name: syslog-ng
    state: restarted
    daemon_reload: yes
    enabled: yes
