---
- name: Install Consul
  package: name=consul state=present

- name: Create consul user
  user:
    name: consul
    home: /etc/consul.d
    system: yes
    shell: /usr/bin/false
    state: present

- name: Create data directory
  file:
    path: /opt/consul
    state: directory
    owner: consul
    group: consul
    mode: 0755

- name: Check if Consul TLS CA, certifacte and key exists
  stat: path="/etc/consul.d/{{ item }}"
  with_items:
    - "consul-{{ consul_mode }}-ca.crt"
    - "consul-{{ consul_mode }}.crt"
    - "consul-{{ consul_mode }}.key"
  register: _check_consul_cert

- name: Set 'consul_cert_exists'
  set_fact: consul_cert_exists="{{ _check_consul_cert.results | sum(attribute='stat.exists') == _check_consul_cert.results | length }}"

- name: Copy config
  template:
    src: "consul.hcl.j2"
    dest: "/etc/consul.d/consul.hcl"
    owner: consul
    group: consul
    mode: 0644

- name: Copy systemd service
  template:
    src: "consul.service.j2"
    dest: "/etc/systemd/system/consul.service"
    mode: 0644

- name: Start consul service
  systemd:
    name: consul
    state: restarted
    daemon_reload: yes
    enabled: yes
